apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lancedb-pvc
  labels:
    app: insur-rag
spec:
  # 對應 OKE 的 Block Volume
  storageClassName: "oci-bv"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # OCI 低消 50G，剛好給 LanceDB + Model Cache 用
      storage: 50Gi